### ISSUE TITLE
Tableau d'avancement obsolète

### ISSUE THREAD

**Issue by Ettapp** [demahom18/vue3-docs-fr-translation-advancement#1]
Bonjour,

Je cherche à trouver quelles traductions restent à faire, compléter ou mettre à jour, malheureusement il semblerait que le tableau d'avancement soit obsolète...

Est-il possible de le mettre à jour ?

Merci d'avance !

**Comment by demahom18** [comment]
Salut @Ettapp, je viens de mettre à jour le tableau d'avancement
